# NameServer ??
rocketmq.name-server=127.0.0.1:9876

# Producer ?? - ???????? Map
rocketmq.producers[producer-IC].group=producer-IC-group
rocketmq.producers[producer-IC].topics[topic1]=producer-IC-group_topic_1
rocketmq.producers[producer-IC].topics[topic2]=producer-IC-group_topic_2

rocketmq.producers[producer-TC].group=producer-TC-group
# ? topics Map ????

rocketmq.producers[producer-SMS].group=producer-SMS-group

rocketmq.producers[producer-TIMEOUT].group=producer-TIMEOUT-group

# Consumer ??
rocketmq.consumers[consumer-SMS].group=consumer-SMS-group
rocketmq.consumers[consumer-SMS].topic=topic_SMS_topic
rocketmq.consumers[consumer-SMS].tag=topic_SMS_topic_TCC

rocketmq.consumers[consumer-TIMEOUT].group=consumer-TIMEOUT-group
rocketmq.consumers[consumer-TIMEOUT].topic=topic_TIMEOUT_topic
rocketmq.consumers[consumer-TIMEOUT].tag=
rocketmq.consumers[consumer-TIMEOUT].listenerClass=