rocketmq:
  nameserver: 127.0.0.1:9876
  producers:
    producer-TC-order:
      group: producer-TC-order-group
      topics:
        TC_order_create_topic: TC_order_create_topic
    producer-TC-order-expired:
      group: producer-TC-order-expired-group
      topics:
        TC_order_expired_delay_topic: TC_order_expired_delay_topic
    producer-TC-payment-expired:
      group: producer-TC-payment-group
      topics:
        TC_payment_topic: TC_payment_topic
    producer-SESSION:
      group: producer-SESSION-group
      topics:
        session_expired_delay_topic: session_expired_delay_topic
    producer-NOTIFICATION-sms:
      group: producer-notification-sms-group
      topics:
        sms_notification_topic: sms_notification_topic
        web_notification_web_topic:  web_notification_web_topic
  consumers:
    consumer-TC-order:
      group: consumer-TC-order-group
      topic: TC_order_create_topic
      tags:
        create-tag: CREATE
        pay-success-tag: PAY_SUCCESS
        cancel-tag: CANCEL
      listenerClass: "com.airfree.mq.core.listener.rocketMq.AirRocketmqMessageConcurrentlyListener"
      instanceNums: 2
    consumer-TC-order-expired:
      group: consumer-TC-order-expired-group
      topic: TC_order_expired_delay_topic
      listenerClass: "com.airfree.mq.core.listener.rocketMq.AirRocketmqMessageConcurrentlyListener"
    consumer-TC-payment-expired:
      group: consumer-TC-payment-expired-group
      topic: TC_payment_topic
      tags:
        P2P-tag: P2P
        B2B-tag: B2B
        P2B-tag: P2B
        B2P-TAG: B2P
      listenerClass: "com.airfree.mq.core.listener.rocketMq.AirRocketmqMessageConcurrentlyListener"
    consumer-SESSION-expired:
      group: consumer-SESSION-expired-group
      topic: session_expired_delay_topic
      tags:
        pc-tag: pc
        mobile-tag: mobile
      listenerClass: "com.airfree.mq.core.listener.rocketMq.AirRocketmqMessageConcurrentlyListener"
    consumer-NOTIFICATION-SMS:
      group: consumer-NOTIFICATION-SMS-group
      topic: sms_notification_topic
      tags:
        order-tag: order
        payment-tag: payment
      listenerClass: "com.airfree.mq.core.listener.rocketMq.AirRocketmqMessageConcurrentlyListener"
    consumer-NOTIFICATION-WEB:
      group: consumer-NOTIFICATION-WEB-group
      topic: web_notification_web_topic
      tags:
        order-tag: order
        payment-tag: payment
      listenerClass: "com.airfree.mq.core.listener.rocketMq.AirRocketmqMessageConcurrentlyListener"