rocketmq:
  nameserver: 127.0.0.1:9876
  producers:
    producerIC:
      group: producer-IC-group
      topics:
        topic1: producer-IC-group_topic_1
        topic2: producer-IC-group_topic_2
    producerTC:
      group: producer-TC-group
      topics: {}
    producer-SMS:
      group: producer-SMS-group
      topics: {}
    producer-TIMEOUT:
      group: producer-TIMEOUT-group
      topics: {}
  consumers:
    consumer-TIMEOUT:
      group: consumer-TIMEOUT-group
      topic: topic_TIMEOUT_topic
      tag: ""
      listenerClass: "com.airfree.mq.core.AirGenericMessageConcurrentlyListener"